package vista;

import controlador.ContactosController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DevBuster
 */
public class Main extends javax.swing.JFrame {

    ContactosController contactosController = new ContactosController();
    DefaultTableModel modeloTabla;
    Object columnas[] = {"ID", "NOMBRE", "APELLIDO", "TELEFONO"};
    Object fila[][] = contactosController.listarContactos();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        this.setTitle("Sistema de Gestión de Contactos - Dashboard");
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        modeloTabla = new DefaultTableModel(fila, columnas);
        tblContactos.setModel(modeloTabla);

        lblUsuario.setText("DevBuster");

        contactosController.listarContactos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeBienvenida = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        mbrMain = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCuenta = new javax.swing.JMenu();
        mitSalir = new javax.swing.JMenuItem();
        mitFinalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMensajeBienvenida.setText("Bienvenido al Sistema:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblContactos);

        menuOpciones.setText("Opciones");

        jMenuItem1.setText("Gestionar Contactos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuOpciones.add(jMenuItem1);

        mbrMain.add(menuOpciones);

        menuCuenta.setText("Cuenta");

        mitSalir.setText("Salir");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        menuCuenta.add(mitSalir);

        mitFinalizar.setText("Finalizar");
        mitFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitFinalizarActionPerformed(evt);
            }
        });
        menuCuenta.add(mitFinalizar);

        mbrMain.add(menuCuenta);

        setJMenuBar(mbrMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensajeBienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensajeBienvenida)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitFinalizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new Contactos().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar mbrMain;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem mitFinalizar;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JTable tblContactos;
    // End of variables declaration//GEN-END:variables
}
